name: CI

on:
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore backend/backend.csproj

      - name: Build
        run: dotnet build backend/backend.csproj --configuration Release --no-restore

      - name: Run tests with coverage
        run: |
          dotnet test backend.Tests/backend.Tests.csproj \
            --configuration Release \
            --no-build \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=./coverage/ \
            /p:ThresholdType=line \
            /p:Threshold=70

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend
